In [2]:
import pandas as pd

df = pd.read_csv('/content/AB_NYC_2019.csv')

print("First 5 rows of the dataset:")
display(df.head())

print(f"\nNumber of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

First 5 rows of the dataset:

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

Number of rows: 48895
Number of columns: 16

In [3]:
missing_values = df.isnull().sum()
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_df = pd.DataFrame({
    'Missing Count': missing_values,
    'Missing Percentage': missing_percentage
})

print("Missing values in each column:")
display(missing_df[missing_df['Missing Count'] > 0].sort_values(by='Missing Count', ascending=False))

Missing values in each column:

                   Missing Count  Missing Percentage
reviews_per_month          10052           20.558339
last_review                10052           20.558339
host_name                     21            0.042949
name                          16            0.032723

In [ ]:
# Create a copy of the DataFrame to perform cleaning operations
df_cleaned = df.copy()

### Handling Missing Values

*   **`name` and `host_name`**: These columns have a very small number of missing values (0.03% and 0.04% respectively). Dropping these rows will have a minimal impact on the dataset size while ensuring data integrity for these key identifiers.
*   **`reviews_per_month`**: This column has a significant number of missing values (over 20%). It is reasonable to assume that a missing value here indicates no reviews for that listing, so we will fill these `NaN` values with `0`.
*   **`last_review`**: This date column also has over 20% missing values, correlating with `reviews_per_month`. When converted to a datetime type, `NaN` values will naturally become `NaT` (Not a Time), which is a suitable representation for an absent date in a datetime column.

In [5]:
# Create a copy of the DataFrame to perform cleaning operations
df_cleaned = df.copy()

# Drop rows where 'name' or 'host_name' are missing
initial_rows = df_cleaned.shape[0]
df_cleaned.dropna(subset=['name', 'host_name'], inplace=True)
rows_dropped_name_host = initial_rows - df_cleaned.shape[0]
print(f"Dropped {rows_dropped_name_host} rows due to missing 'name' or 'host_name'.")

# Fill missing 'reviews_per_month' with 0
df_cleaned['reviews_per_month'].fillna(0, inplace=True)

# Convert 'last_review' to datetime. Missing values will become NaT.
df_cleaned['last_review'] = pd.to_datetime(df_cleaned['last_review'])

Dropped 37 rows due to missing 'name' or 'host_name'.

/tmp/ipykernel_11989/14504399.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned['reviews_per_month'].fillna(0, inplace=True)

After these operations, let's re-check the missing values and the DataFrame information to confirm the changes.

In [6]:
print("Missing values after cleaning:")
missing_after_cleaning = df_cleaned.isnull().sum()
display(missing_after_cleaning[missing_after_cleaning > 0])

print("\nDataFrame info after cleaning:")
df_cleaned.info()

Missing values after cleaning:

last_review    10037
dtype: int64

DataFrame info after cleaning:
<class 'pandas.core.frame.DataFrame'>
Index: 48858 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48858 non-null  int64
 1   name                            48858 non-null  object
 2   host_id                         48858 non-null  int64
 3   host_name                       48858 non-null  object
 4   neighbourhood_group             48858 non-null  object
 5   neighbourhood                   48858 non-null  object
 6   latitude                        48858 non-null  float64
 7   longitude                       48858 non-null  float64
 8   room_type                       48858 non-null  object
 9   price                           48858 non-null  int64
 10  minimum_nights                  48858 non-null  int64
 11  number_of_reviews               48858 non-null  int64
 12  last_review                     38821 non-null  datetime64[ns]
 13  reviews_per_month               48858 non-null  float64
 14  calculated_host_listings_count  48858 non-null  int64
 15  availability_365                48858 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(7), object(5)
memory usage: 6.3+ MB

In [7]:
print("First 5 rows of the cleaned dataset:")
display(df_cleaned.head())


print(f"\nNumber of rows in cleaned dataset: {df_cleaned.shape[0]}")
print(f"Number of columns in cleaned dataset: {df_cleaned.shape[1]}")

First 5 rows of the cleaned dataset:

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaT,0.00,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

Number of rows in cleaned dataset: 48858
Number of columns in cleaned dataset: 16

In [8]:
initial_rows_before_dropping_duplicates = df_cleaned.shape[0]

duplicate_rows = df_cleaned.duplicated().sum()
print(f"Number of duplicate rows found: {duplicate_rows}")

# Drop duplicate rows
df_cleaned.drop_duplicates(inplace=True)

rows_dropped_duplicates = initial_rows_before_dropping_duplicates - df_cleaned.shape[0]
print(f"Dropped {rows_dropped_duplicates} duplicate rows.")
print(f"Number of rows after removing duplicates: {df_cleaned.shape[0]}")

Number of duplicate rows found: 0
Dropped 0 duplicate rows.
Number of rows after removing duplicates: 48858

### Data Standardization

Standardization is a data preprocessing technique used to scale numerical features so that they have a mean of 0 and a standard deviation of 1. This is particularly useful for many machine learning algorithms that are sensitive to the scale of input features.

We will apply standardization to the numerical columns of the `df_cleaned` DataFrame to ensure consistent scaling.

In [9]:
from sklearn.preprocessing import StandardScaler

# Identify numerical columns for standardization
numerical_cols = df_cleaned.select_dtypes(include=['int64', 'float64']).columns.tolist()

# Exclude 'id' and 'host_id' as they are identifiers and not features to be scaled
# 'number_of_reviews' and 'calculated_host_listings_count' are counts and can be scaled
numerical_cols_to_scale = [col for col in numerical_cols if col not in ['id', 'host_id']]

print(f"Numerical columns identified for standardization: {numerical_cols_to_scale}")

# Initialize the StandardScaler
scaler = StandardScaler()

# Apply StandardScaler to the selected numerical columns
df_cleaned[numerical_cols_to_scale] = scaler.fit_transform(df_cleaned[numerical_cols_to_scale])

print("\nFirst 5 rows of the DataFrame after standardization of numerical columns:")
display(df_cleaned[numerical_cols_to_scale].head())

Numerical columns identified for standardization: ['latitude', 'longitude', 'price', 'minimum_nights', 'number_of_reviews', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365']

First 5 rows of the DataFrame after standardization of numerical columns:

,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
0,-1.493773,-0.437612,-0.015570,-0.300329,-0.320388,-0.551649,-0.034837,1.916263
1,0.452597,-0.684585,0.300794,-0.300329,0.487703,-0.445217,-0.156180,1.840280
2,1.468605,0.222498,-0.011407,-0.200426,-0.522411,-0.683125,-0.186516,1.916263
3,-0.803291,-0.164426,-0.265330,-0.300329,5.538271,2.221862,-0.186516,0.616965
4,1.275857,0.177220,-0.302795,0.149232,-0.320388,-0.620518,-0.186516,-0.857091

In [10]:
# Identify numerical columns for outlier detection (excluding identifiers and 'last_review')
numerical_cols_for_outliers = [col for col in df_cleaned.select_dtypes(include=['int64', 'float64']).columns if col not in ['id', 'host_id']]

print("Outlier Detection using IQR Method:")

outlier_summary = {}
for col in numerical_cols_for_outliers:
    Q1 = df_cleaned[col].quantile(0.25)
    Q3 = df_cleaned[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Count outliers
    outliers = df_cleaned[(df_cleaned[col] < lower_bound) | (df_cleaned[col] > upper_bound)]
    num_outliers = outliers.shape[0]

    if num_outliers > 0:
        outlier_summary[col] = num_outliers
        print(f"  Column '{col}': {num_outliers} outliers found.")

if not outlier_summary:
    print("  No significant outliers detected using the IQR method for the selected numerical columns.")

# Note: This step only identifies outliers. Further action (e.g., capping, removal) would depend on the specific analysis goals.

Outlier Detection using IQR Method:
  Column 'latitude': 425 outliers found.
  Column 'longitude': 2832 outliers found.
  Column 'price': 2976 outliers found.
  Column 'minimum_nights': 6605 outliers found.
  Column 'number_of_reviews': 6015 outliers found.
  Column 'reviews_per_month': 3309 outliers found.
  Column 'calculated_host_listings_count': 7080 outliers found.